apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    name: dev-cluster
  project: default
  source:
    path: .
    repoURL: https://github.com/Olek-Serdiuk/k8s-dashboard.git
    targetRevision: HEAD
