apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashboard
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kubernetes-dashboard
    server: 'https://kubernetes.default.svc'
  source:
    path: /
    repoURL: 'https://github.com/Olek-Serdiuk/k8s-dashboard.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=background
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2