apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: overlays/prod/
    repoURL: https://github.com/Olek-Serdiuk/k8s-dashboard.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false